### ISSUE TITLE
Spell check

### ISSUE THREAD

**Issue by tesar-tech** [Beyond-Skills-Training-Global/bst-tw-design#15]
Please also check spelling on texts. 
These are services I was talking about, they may help: 

https://www.online-spellcheck.com/
https://datayze.com/website-spell-checker
https://www.grammar.com/check-website.php
https://chrome.google.com/webstore/detail/webpage-spell-check/mgdhaoimpabdhmacaclbbjddhngchjik
plugin to vs code
https://github.com/streetsidesoftware/vscode-spell-checker
https://github.com/bartosz-antosik/vscode-spellright

**Comment by rajdevkar** [comment]
I haven't found any spelling errors on the home and other pages. I have installed the vs code extension for spell check. Please do let me know if there are any other ones.

**Comment by tesar-tech** [comment]
I have found a lot of them with the second extension (spellright). It hase also workspace white list: https://github.com/Beyond-Skills-Training-Global/bst-tw-design/blob/dev-branch/.vscode/spellright.dict
I advice you to use the same and do spell check on the go. (I had to add .html into source code to check in extension settings).
