### ISSUE TITLE
Highlight navbar active menu item on scroll

### ISSUE THREAD

**Issue by ravi-sankarp** [Beyond-Skills-Training-Global/bst-tw-design#18]
Now the navbar active menu item is fixed to home section. <br>
It would be nice if it changes on scroll.That is it changes the active class to the section user is currently in.

This is my first contribution in github.
So please forgive me if I am not following proper guidelines.

**Comment by tesar-tech** [comment]
Nice, that's correct, it should be active. 
@rajdevkar have you got any suggestions?

**Comment by ravi-sankarp** [comment]
I have been learning html,css,js for the past couple of months.
I have also done small projects.
So if its okay with the team maintainer I would like to develop this feature.

**Comment by tesar-tech** [comment]
Well yes. But the pages are not static. Hero section is not actually repeated in every page (here yes, it is just for testing). So it needs a solution that would check current url. Are you still up to this task @ravi-sankarp?

**Comment by ravi-sankarp** [comment]
I didn't read the full code base.
So you are saying that you guys are not building a single page layout.
You guys are planning to implement each item on the navbar on a separate html file.

**Comment by RahulSulegoakar** [comment]
yes, it is a multipage website.

**Comment by ravi-sankarp** [comment]
So when would the full implementation be completed.
Currently the links are not working right?

**Comment by tesar-tech** [comment]
This repo and it's github page is only "preview" for converting design to html/css (tailwind).
This will be converted to https://bst.coach, where it runs on asp.net core razor pages. 
These are mostly static pages so there is "almost" full copy to asp.net core. One of the exception is header and footer. Here we have it in all pages, but it's tedious work to keep i up to date (for example when something changes in menu, we would have to edit it on every page). So we decided to keep header and footer up to date only in the index page. 
When converted to asp.net core header and footer will be created only ones as a "partial" and placed into every page through one line of code...
So for the feature we are talking about, it's perfectly fine to created on index page only. If it works dynamically on index, it will also work on every other page, that use header "partial"..

**Comment by ravi-sankarp** [comment]
Okay...
Anyway good luck.

**Comment by RahulSulegoakar** [comment]
@tesar-tech I think we should close this

**Comment by tesar-tech** [comment]
It is still unresolved. Maybe it is not issue at all...
I don't know which solution is the best one. I found some "js only" and some that are related to razor pages. But none of them feels right..

**Comment by ravi-sankarp** [comment]
I think you should close it for now.And when all the sub-pages are updated just think about it...
