### ISSUE TITLE
Sub menu for "Services"

### ISSUE THREAD

**Issue by tesar-tech** [Beyond-Skills-Training-Global/bst-tw-design#19]
Should be 3 sub buttons there:

Training Platform 
Personal Training
Coaching Consultations 

(in this order)

Please re-use or parametrize existing toggle function for that (on mobile).

**Comment by rajdevkar** [comment]
Added this in home page should I copy it in every page ?

**Comment by tesar-tech** [comment]
Index is enough.

**Comment by tesar-tech** [comment]
It works, but there is whole new function for that. There is already toggleAvoutUs which is almost the same. Please rename it, parametrize it an reuse it as I requested in this issue description. 
Otherwise it creates technical dept for future me.
