### ISSUE TITLE
get to know us on mobile - read more doesn't work

### ISSUE THREAD

**Issue by tesar-tech** [Beyond-Skills-Training-Global/bst-tw-design#20]
when you tap that, it should roll down like this: 
![image](https://user-images.githubusercontent.com/33880579/178212647-2232b724-5bff-479b-b7e6-802f0fcc4cd2.png)

Please use summary and detail html elements for this if possible.

**Comment by rajdevkar** [comment]
I have done functionality. Let me know the content doc link or something. Will change it according
