### ISSUE TITLE
FAQ - some js issues

### ISSUE THREAD

**Issue by tesar-tech** [Beyond-Skills-Training-Global/bst-tw-design#26]
- it throws errors when opening. 
> Uncaught TypeError: Cannot read properties of null (reading 'classList')
    at toggleFaq (faq.html:863:29)
    at HTMLButtonElement.onclick (faq.html:490:298)
- remove unnecessary js (swiper)
- place page related js to separate <script>, keep the header js in separate <script> (header first, page second). This should be rule for all new pages.

**Comment by tesar-tech** [comment]
As we discussed - app.js should be inside header - all of the pages uses that script. 
On the other hand data.js should be only where is needed (and outside of the header).
Also please split the data.js into data-index.js and data-faq and place this file accordingly (also discussed).

**Comment by rajdevkar** [comment]
Placed site.js in head, converted data.js into two separate files data-testimonial 664b6ae36c9693a91bce55cc04a16479397eb6e1 and data-faq also called them outside head tag in files that require it.
