### ISSUE TITLE
Duplicates in index.html

### ISSUE THREAD

**Issue by tesar-tech** [Beyond-Skills-Training-Global/bst-tw-design#30]
Why do we have this element: 
https://github.com/Beyond-Skills-Training-Global/bst-tw-design/blob/3ed0739c2134be2883aed2d71ff3264979c7fa1f/wwwroot/index.html#L383

which is almost the same as:
https://github.com/Beyond-Skills-Training-Global/bst-tw-design/blob/3ed0739c2134be2883aed2d71ff3264979c7fa1f/wwwroot/index.html#L424

?? 

This does creates issues. I was changing the text and links and forget to "mobile" version. 

Can we have it in single element?

**Comment by rajdevkar** [comment]
Combined both of them - 59c89225a3fb9df788bcf692bd2fb8a2b4a09c81

**Comment by tesar-tech** [comment]
Nice!
