### ISSUE TITLE
Look of the page when user is logged in 

### ISSUE THREAD

**Issue by tesar-tech** [Beyond-Skills-Training-Global/bst-tw-design#33]
Currently we have stylet for unauthorized user.  On login page I implemented this: (img 2)... 
There should be link to coach section and name of the logged user (email)... Ideas how to make it ?
![image](https://user-images.githubusercontent.com/33880579/178788986-3211d5f5-f844-48fb-a615-b92af89161b9.png)
![image](https://user-images.githubusercontent.com/33880579/178789007-39b53b0e-8d9a-4d08-86ff-884f9df53c94.png)

**Comment by hfridrik** [comment]
Your request is being processed : )

**Comment by hfridrik** [comment]
Desktop Version (2 Variants):
![Logged in look-desktop](https://user-images.githubusercontent.com/109089673/179235211-4b4deaac-91ca-42f0-ba99-18f53d673a09.png)

**Comment by hfridrik** [comment]
Mobile Version (2 variants):
![Logged in look-mobile](https://user-images.githubusercontent.com/109089673/179235311-9fa75aec-25c1-4075-988e-48f469ead1a0.png)
