### ISSUE TITLE
Personal training page

### ISSUE THREAD

**Issue by tesar-tech** [Beyond-Skills-Training-Global/bst-tw-design#34]
CHOOSE YOUR PLAN
we can become your personal trainer

Recognizing the demand for online strength training, BST.COACH also offers affordable online training plans. Tell us a little bit about yourself that would help us build an optimal training program tailored for your specific needs.

**Comment by hfridrik** [comment]
Ok, text is updated.

**Comment by hfridrik** [comment]
COACHING CONSULTATIONS
we help find performance breakthroughs

If you simply need to bounce your ideas off of another passionate sports performance mind, we offer Zoom calls and help coaches and athletes crystalize the best solutions to coaching and training needs

**Comment by tesar-tech** [comment]
All the text:

PERSONAL TRAINING

CHOOSE YOUR PLAN
we can become your personal trainer

Recognizing the demand for online strength training, BST.COACH also offers affordable online training plans. Tell us a little bit about yourself that would help us build an optimal training program tailored for your specific needs.

Name
Surname
Enter your email
Leave a message...

SUBMIT

*LIABILITY DISCLAIMER
Injuries of all types are always a possibility when participating in vigorous activities, including when following online fitness programs. BST.COACH recommends that you obtain a comprehensive health examination from a licensed physician prior to undertaking any of our training plans. 

BST.COACH does not take liability for any injury or health problem caused during or after execution of our training plans. Each individual is responsible to practice caution when following ANY of our exercise video demonstrations and training prescriptions.

COACHING CONSULTATIONS

COACHING CONSULTATIONS
we help find performance breakthroughs

If you simply need to bounce your ideas off of another passionate sports performance mind, we offer Zoom calls and help coaches and athletes crystalize the best solutions to coaching and training needs. 

€40 PER HOUR

Name
Surname
Enter your email
Leave a message about your time/date preferences

SUBMIT

**Comment by rajdevkar** [comment]
I think we can close this issue thread
