### ISSUE TITLE
Design comments on Main Page

### ISSUE THREAD

**Issue by hfridrik** [Beyond-Skills-Training-Global/bst-tw-design#36]
I've made some design-related comments mainly concerning the main page. 
Let me know if I can help you anyhow to make changes : )  
[Design-comments of main page.pdf](https://github.com/Beyond-Skills-Training-Global/bst-tw-design/files/9121579/Design-comments.of.main.page.pdf)

**Comment by tesar-tech** [comment]
@rajdevkar  For the 5 - I think it can be solved by negative 1px margine.

**Comment by rajdevkar** [comment]
@hfridrik I think this issue is resolved can you check and close this issue.
