### ISSUE TITLE
Inconsistent level on pricing

### ISSUE THREAD

**Issue by tesar-tech** [Beyond-Skills-Training-Global/bst-tw-design#37]
These heading should be on a same level 
![image](https://user-images.githubusercontent.com/33880579/180203018-802c7549-a747-44ed-849e-bcad033c4a06.png)

Also on desktop it should keeps consistent heights when content is change a bit.

**Comment by Reinis-K** [comment]
Good catch

**Comment by tesar-tech** [comment]
Also we decided to have just one order (Open Library, coach plan, team plan). This should make it easier to maintain.

**Comment by Reinis-K** [comment]
Yea. I was counting on it. Hanna had taken a smart initiative on it that made sense to me from the beginning. Slipped out of my sight that the front page has to be changed back to the original order: Free -> Coach -> Team.

**Comment by tesar-tech** [comment]
Now the level is inconsistent for prices & get now button
![image](https://user-images.githubusercontent.com/33880579/182909679-5f5e7f50-94b1-40b7-9583-3f35a6f96be6.png)

**Comment by tesar-tech** [comment]
Also please replace the coming soon text with button "Request now". 

From the functional perspective - it should be able to handle multiple item in pricing with different numbers of them in each boxes (so no fixed heights).

**Comment by rajdevkar** [comment]
<img width="1084" alt="Screenshot 2022-08-05 at 6 36 12 PM" src="https://user-images.githubusercontent.com/17295430/183083562-ad746fa7-07be-4479-b94a-f1bb300b149b.png">
Like this ?

**Comment by tesar-tech** [comment]
Yes, looks good. Now just the order to be right. Open lib, coach plan and team plan
