### ISSUE TITLE
Pricing page

### ISSUE THREAD

**Issue by tesar-tech** [Beyond-Skills-Training-Global/bst-tw-design#38]
We agreed it should be 1 page with 3 headings with Open Library, Coach plan, Team plan.. (we will use anchors, to let user see exactly what they clicked (if they click coach plan it will scroll automatically to coach plan)). 
Under each heading there will be described features. Just well styled document. @Reinis-K  is working on that.

Also get now button should be present on each plan.. Problem is how to solve the annual-monthly switch..

Ideas?

**Comment by Reinis-K** [comment]
What exactly is the problem with the monthly switch? Was that question to
me?

**Comment by tesar-tech** [comment]
More for Hanna I think... 
Problem is - we don't have that pricing table in pricing options. So the monthly switch has to be modified somehow.

**Comment by Reinis-K** [comment]
Pricing details text:

@hfridrik @tesar-tech  Please check it and decide how to implement it. Communicate about this with each other, please. Ask if something necessary from me.

https://docs.google.com/document/d/1MIJkA-kymQpW2JaYo6LWLu7aRivfMG60CLbBHDb9DBo/edit?usp=sharing

**Comment by hfridrik** [comment]
Hello @rajdevkar 

I've encountered the issue when opening pricing page on phone (iOS), using Safari, Firefox and DuckDuckGo..
For some reason, the design looks a little broken. Are there any specific reasons why it is so?

Thank you : ) 

![Pricing-mobile](https://user-images.githubusercontent.com/109089673/184336206-9d6a645e-e92a-4bc2-b62e-1037eee838bd.png)
