### ISSUE TITLE
Links in index.html

### ISSUE THREAD

**Issue by tesar-tech** [Beyond-Skills-Training-Global/bst-tw-design#5]
Activate links in index page. "join bst" leads to `registration`, link for demo training is in links channel on discord. 

if the link have multiple words, merge them into one (getusknow),

Also the links in the footer should be active

**Comment by tesar-tech** [comment]
@rajdevkar can you address this asap now? Push right to the main branch if necessary.

**Comment by rajdevkar** [comment]
Added links in both home and features page @tesar-tech can you check once and confirm they are correct. Also can you provide facebook and LinkedIn links as they are missing from linktree.

**Comment by tesar-tech** [comment]
I think it's fine. Only the lion logo and text should be `./` instead of just `/`. 
About the links -> there is ongoing discussion on discord on that.

**Comment by rajdevkar** [comment]
Changed lion logo link from `/` to `./` in ec9d70345703f2e34663461048bbdd82a5af780c

**Comment by tesar-tech** [comment]
We should have changed base tag for gh pages (in pipeline) . That it would work with absolute links as it should in all environments.. Nvm, I will fix it later.
