### ISSUE TITLE
Line breaks in html elements

### ISSUE THREAD

**Issue by tesar-tech** [Beyond-Skills-Training-Global/bst-tw-design#9]
Many times I encountered this: 

![image](https://user-images.githubusercontent.com/33880579/178060277-2bfb998d-5b03-42eb-ab14-0ec9888098f2.png)

I am not sure where it comes from or why is it happening, but we need to be consistent in this. 
Because otherwise it pollute the git changes and can potentially hide something important.

Do you (@rajdevkar) know why is line breaking happening? you do it purposefully or is it your ide?    

We should stick with non-line-breaking solution.

**Comment by rajdevkar** [comment]
Its actually vscode prettier plugin. what do you use for indentation.

**Comment by tesar-tech** [comment]
It is not about indentation (as you can see on right side), it's about wrapping. 

For indentation I use build in functionality of vscode (didn't change anything). And I don't use any wrapping.

Can you go with soft wrapping (it should be settings in vscode) instead of current line breaking?
